#!/usr/bin/env bash
# controller.sh — slurmctld (controller node) setup
# Sourced by install.sh; requires common.sh to be loaded first.

install_controller_packages() {
    log_step "Installing controller packages"

    apt_install slurmctld slurm-client slurm-wlm-basic-plugins

    log_success "Controller packages installed."
}

generate_slurm_conf() {
    log_step "Generating slurm.conf"

    local conf_file="/etc/slurm/slurm.conf"
    local template="${SCRIPT_DIR}/config/templates/slurm.conf.tmpl"

    if [[ -f "$conf_file" ]]; then
        if confirm "Existing slurm.conf found. Overwrite?" "default_no"; then
            backup_file "$conf_file"
        else
            log_info "Keeping existing slurm.conf."
            return 0
        fi
    fi

    # Build accounting storage lines
    local acct_type="accounting_storage/none"
    local acct_extra="# No accounting database configured."

    if [[ "${NODE_ROLE}" == "controller_db" ]]; then
        acct_type="accounting_storage/slurmdbd"
        acct_extra="AccountingStorageHost=localhost"
    elif [[ -n "${DBD_HOSTNAME:-}" ]]; then
        acct_type="accounting_storage/slurmdbd"
        acct_extra="AccountingStorageHost=${DBD_HOSTNAME}"
    fi

    # Build node definitions
    local node_defs=""
    local partition_defs=""

    if [[ -n "${COMPUTE_NODES:-}" ]]; then
        node_defs="$COMPUTE_NODES"
        # Extract node names for the partition line
        local node_names
        node_names=$(echo "$COMPUTE_NODES" | grep -oP 'NodeName=\K[^\s]+' | paste -sd',' -)
        partition_defs="PartitionName=${PARTITION_NAME:-batch} Nodes=${node_names} Default=YES MaxTime=INFINITE State=UP"
    else
        node_defs="# No compute nodes configured yet."
        node_defs="${node_defs}"$'\n'"# Run 'slurmd -C' on each compute node and add the output here."
        node_defs="${node_defs}"$'\n'"# Example:"
        node_defs="${node_defs}"$'\n'"# NodeName=compute01 CPUs=16 RealMemory=64000 Sockets=1 CoresPerSocket=8 ThreadsPerCore=2 State=UNKNOWN"
        partition_defs="# PartitionName=batch Nodes=compute[01-10] Default=YES MaxTime=INFINITE State=UP"
    fi

    # Determine GRES types based on whether any node has GPU resources
    local gres_types=""
    if echo "${COMPUTE_NODES:-}" | grep -qE 'Gres=gpu'; then
        gres_types="GresTypes=gpu"
    else
        gres_types="# GresTypes=gpu  # Uncomment if you add GPU nodes"
    fi

    declare -A vars=(
        [GENERATED_DATE]="$(date '+%Y-%m-%d %H:%M:%S')"
        [CLUSTER_NAME]="${CLUSTER_NAME}"
        [CONTROLLER_HOSTNAME]="${CONTROLLER_HOSTNAME}"
        [ACCOUNTING_STORAGE_TYPE]="${acct_type}"
        [ACCOUNTING_STORAGE_EXTRA]="${acct_extra}"
        [GRES_TYPES]="${gres_types}"
        [NODE_DEFINITIONS]="${node_defs}"
        [PARTITION_DEFINITIONS]="${partition_defs}"
    )

    render_template "$template" "$conf_file" vars

    chown root:root "$conf_file"
    chmod 0644 "$conf_file"

    log_success "slurm.conf written to ${conf_file}."
    log_info "This file must be copied identically to all other cluster nodes."
}

generate_cgroup_conf() {
    local conf_file="/etc/slurm/cgroup.conf"
    local template="${SCRIPT_DIR}/config/templates/cgroup.conf.tmpl"

    if [[ -f "$conf_file" ]]; then
        log_info "cgroup.conf already exists, keeping it."
        return 0
    fi

    declare -A vars=(
        [GENERATED_DATE]="$(date '+%Y-%m-%d %H:%M:%S')"
    )

    render_template "$template" "$conf_file" vars

    chown root:root "$conf_file"
    chmod 0644 "$conf_file"

    log_info "cgroup.conf written to ${conf_file}."
}

# Generate gres.conf for GPU support (controller-as-compute case).
# Dynamically generates gres.conf based on which GPU plugins are installed.
# Only called when CONTROLLER_IS_COMPUTE=true.
generate_gres_conf() {
    local conf_file="/etc/slurm/gres.conf"

    if [[ -f "$conf_file" ]]; then
        log_info "gres.conf already exists, keeping it."
        return 0
    fi

    # Check which GPU plugins are installed
    local has_nvml=false
    local has_rsmi=false

    if dpkg -l slurm-wlm-nvml-plugin 2>/dev/null | grep -q '^ii'; then
        has_nvml=true
    fi
    if dpkg -l slurm-wlm-rsmi-plugin 2>/dev/null | grep -q '^ii'; then
        has_rsmi=true
    fi

    # Only create gres.conf if at least one GPU plugin is installed
    if ! $has_nvml && ! $has_rsmi; then
        log_info "No GPU plugins installed — skipping gres.conf."
        return 0
    fi

    # Generate gres.conf with only the installed plugins
    {
        echo "# gres.conf — Generated by slurm-installer on $(date '+%Y-%m-%d %H:%M:%S')"
        echo "# Auto-detection discovers GPUs without manual enumeration."
        echo ""
        if $has_nvml; then
            echo "# NVIDIA GPU detection via NVML"
            echo "AutoDetect=nvml"
        fi
        if $has_rsmi; then
            echo "# AMD GPU detection via RSMI"
            echo "AutoDetect=rsmi"
        fi
    } > "$conf_file"

    chown root:root "$conf_file"
    chmod 0644 "$conf_file"

    local plugins=""
    $has_nvml && plugins="nvml"
    $has_rsmi && plugins="${plugins:+$plugins, }rsmi"
    log_success "gres.conf written to ${conf_file} (AutoDetect: ${plugins})."
}

start_slurmctld() {
    log_step "Starting slurmctld"
    setup_service_defaults "slurmctld" "SLURMCTLD_OPTIONS"
    enable_and_start slurmctld
}

register_cluster() {
    log_step "Registering cluster in accounting database"

    if [[ "${NODE_ROLE}" != "controller_db" && -z "${DBD_HOSTNAME:-}" ]]; then
        log_info "No accounting database — skipping cluster registration."
        return 0
    fi

    # Wait a moment for slurmdbd to be fully ready
    sleep 2

    # Check if cluster is already registered
    if sacctmgr -n show cluster "${CLUSTER_NAME}" 2>/dev/null | grep -Fqw "${CLUSTER_NAME}"; then
        log_info "Cluster '${CLUSTER_NAME}' is already registered."
    else
        sacctmgr -i add cluster "${CLUSTER_NAME}"
        log_success "Cluster '${CLUSTER_NAME}' registered."
    fi
}

# Set up default Slurm account and optionally add system users.
# This enables job submission without manual sacctmgr commands.
setup_default_account() {
    log_step "Setting up default Slurm account"

    # Only for roles with accounting database
    if [[ "${NODE_ROLE}" != "controller_db" && -z "${DBD_HOSTNAME:-}" ]]; then
        log_info "No accounting database — skipping account setup."
        return 0
    fi

    # Wait for slurmdbd to be ready
    sleep 2

    local default_account="compute"

    # Create default account if not exists
    if ! sacctmgr -n show account "$default_account" 2>/dev/null | grep -qw "$default_account"; then
        sacctmgr -i add account "$default_account" Description="Default compute account"
        log_success "Created account: ${default_account}"
    else
        log_info "Account '${default_account}' already exists."
    fi

    # Prompt to add current system users
    echo
    if confirm "Add current system users to Slurm accounting?" "default_yes"; then
        setup_slurm_users "$default_account"
    fi
}

# Add system users to Slurm accounting.
# Usage: setup_slurm_users "account_name"
setup_slurm_users() {
    local account="$1"

    # Get list of normal users (UID >= 1000, has login shell)
    local users
    users=$(awk -F: '$3 >= 1000 && $7 !~ /nologin|false/ {print $1}' /etc/passwd)

    if [[ -z "$users" ]]; then
        log_info "No regular users found to add."
        return 0
    fi

    log_info "Found users: $users"
    for user in $users; do
        if ! sacctmgr -n show user "$user" 2>/dev/null | grep -qw "$user"; then
            sacctmgr -i add user "$user" account="$account"
            log_success "Added user: ${user} -> account=${account}"
        else
            log_info "User '${user}' already exists in accounting."
        fi
    done
}

# ── Main entry point ───────────────────────────────────────────────────────

setup_controller() {
    install_controller_packages
    generate_slurm_conf
    generate_cgroup_conf
    start_slurmctld
    register_cluster
    setup_default_account
}
